### ISSUE TITLE
Feedback tp should be same as report command

### ISSUE THREAD

**Issue by jdd-software** [SOBotics/Natty#29]
The feedback tp should work as report command if post is not already present this since it will avoid userscript to have to call Natty or Sentinel api to check if already reported. 

Suggested modification:

`@Natty feedback <link> tp`

should if post is not present `report` the post, hence work as the report command. The check is that post (NATO) is not present and the command is `tp`. The response will be as if it was reported and post will be marked with `tn`

**Comment by Bhargav-Rao** [comment]
This was proposed before (way back when the `feedback` and `report` commands were added and when Tuna wrote the script). The issue then was that the `report` command and the `feedback` command were in two completely different modules. 

Now, in v4, I've been planning to refactor them to use a service, rather than utils. If that's the case, then both `feedback` and `report` would be calling the same service layer. (As of now, [`feedback` uses a util to complete the operation](https://github.com/SOBotics/Natty/blob/master/src/main/java/in/bhargavrao/stackoverflow/natty/commands/Feedback.java#L56), whereas [`report` is yet to be refactored](https://github.com/SOBotics/Natty/blob/master/src/main/java/in/bhargavrao/stackoverflow/natty/commands/Report.java#L76). Ideally, [`PostUtils`](https://github.com/SOBotics/Natty/blob/master/src/main/java/in/bhargavrao/stackoverflow/natty/utils/PostUtils.java) should be a service layer altogether. Once that is done, this would certainly be easy to implement. (A maximum of 1 or 2 lines of extra code). 

Given that I'm held up for 6-8 weeks and almost useless when compared to developing the bot, I'd not promise that the feature would be implemented anytime soon. At the moment, v4 is 75% complete, which means that I'd need atleast 22-25 dev hours more to complete the development of v4, and perhaps 10 more for the testing. (Note that many of the features in v4 like automatic feedback invalidation and the banning of users, would need to be extensively tested before going live).

**Comment by rjrudman** [comment]
@Bhargav-Rao Does this mean that userscripts can now just always use `report {url}`? Is there any difference now between responding `tp` vs just reporting?

**Comment by Bhargav-Rao** [comment]
@rjrudman Not quite, you'll get a "Post already reported" message back. I'd still prefer a feedback, because the report command tries to process it as a new report and then converts it into a feedback, if that particular post is found. A feedback directly stores the post as a feedback.
