### ISSUE TITLE
Add a specific error message when trying to report too new answers

### ISSUE THREAD

**Issue by Filnor** [SOBotics/Natty#34]
When I report an answer to Natty with the command `@Natty report <link to answer>` and the answer is not to an old question, I recieve the following message from Natty:
> Post is not allowed to be reported in this room.

This message doesn't make it clear that I tried to report a too new answer. It would be better to have a specific error message for that, something like:
> Post is not a new answer to an old question.

Or even shorter, although the abbreviation might be confusing for newer users:
> Post is not a NATO.

**Comment by Bhargav-Rao** [comment]
Yeah, this has been on the cards since long. Few starting thoughts: 

1. Firstly the validators do not have a descriptor https://github.com/SOBotics/Natty/tree/master/src/main/java/in/bhargavrao/stackoverflow/natty/validators 
2. In a few places like here, https://github.com/SOBotics/Natty/blob/65638f982c39f2783ee66f38f17d4cf78d5978a0/src/main/java/in/bhargavrao/stackoverflow/natty/commands/Report.java#L50, I need to just change it to "How bout no" or something like that. 
3. Here https://github.com/SOBotics/Natty/blob/65638f982c39f2783ee66f38f17d4cf78d5978a0/src/main/java/in/bhargavrao/stackoverflow/natty/commands/Report.java#L117, I should print out the descriptor of the validator

All this boils down to possibly around 15 lines of code change, which isn't that hard. The primary issue at hand is, I don't really have the time at the moment. I'll probably be doing the rewrite for v4 sometime mid May or June, after which all the pending FRs and Issues would be handled. Sorry for that!

**Comment by pbdevch** [comment]
No problem, I just thought it would be a nice addition and already guessed that it would into v4.
